<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="utf-8">
  
  <title>解决ROS和python3的问题 | Hexo</title>
  <meta name="author" content="John Doe">
  
  <meta name="description" content="ROS原生不支持python3,因此个别包需要在python3环境下进行重新编译,生成对应的文件.
比如在import cv_bridge的时候会出现报错：
12345678Traceback (most recent call last):  File &amp;quot;&amp;#x2F;home&amp;#x2F;">
  
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <meta property="og:title" content="解决ROS和python3的问题"/>
  <meta property="og:site_name" content="Hexo"/>

  
    <meta property="og:image" content=""/>
  

  <link rel="shortcut icon" href="/favicon.png">
  
  
<link rel="stylesheet" href="/css/style.css">

  <!--[if lt IE 9]><script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script><![endif]-->
  

<meta name="generator" content="Hexo 5.1.1"></head>


<body>
  <header id="header" class="inner"><div class="alignleft">
  <h1><a href="/">Hexo</a></h1>
  <h2><a href="/"></a></h2>
</div>
<nav id="main-nav" class="alignright">
  <ul>
    
      <li><a href="/null">Home</a></li>
    
      <li><a href="/archives">Archives</a></li>
    
  </ul>
  <div class="clearfix"></div>
</nav>
<div class="clearfix"></div>
</header>
  <div id="content" class="inner">
    <div id="main-col" class="alignleft"><div id="wrapper"><article id="[post]-ros-python3" class="h-entry [post]" itemprop="blogPost" itemscope itemtype="https://schema.org/BlogPosting">
  
  <div class="post-content">
    <header>
      
        <div class="icon"></div>
        <time class="dt-published" datetime="2020-08-30T22:42:55.000Z"><a href="/2020/08/30/ros-python3/">2020-08-30</a></time>
      
      
  
    <h1 class="p-name title" itemprop="headline name">解决ROS和python3的问题</h1>
  

    </header>
    <div class="e-content entry" itemprop="articleBody">
      
        <p>ROS原生不支持python3,因此个别包需要在python3环境下进行重新编译,生成对应的文件.</p>
<p>比如在<code>import cv_bridge</code>的时候会出现报错：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;&#x2F;home&#x2F;helei&#x2F;catkin_ws_rl&#x2F;src&#x2F;explainable_rl_ros&#x2F;scripts&#x2F;model_evaluation.py&quot;, line 71, in &lt;module&gt;</span><br><span class="line">    node_me &#x3D; ModelEvalNode()</span><br><span class="line">  File &quot;&#x2F;home&#x2F;helei&#x2F;catkin_ws_rl&#x2F;src&#x2F;explainable_rl_ros&#x2F;scripts&#x2F;model_evaluation.py&quot;, line 23, in __init__</span><br><span class="line">    self.bridge &#x3D; CvBridge()</span><br><span class="line">  File &quot;&#x2F;opt&#x2F;ros&#x2F;kinetic&#x2F;lib&#x2F;python2.7&#x2F;dist-packages&#x2F;cv_bridge&#x2F;core.py&quot;, line 67, in __init__</span><br><span class="line">    import cv2</span><br><span class="line">ImportError: &#x2F;opt&#x2F;ros&#x2F;kinetic&#x2F;lib&#x2F;python2.7&#x2F;dist-packages&#x2F;cv2.so: undefined symbol: PyCObject_Type</span><br></pre></td></tr></table></figure>

<h2 id="解决方案"><a href="#解决方案" class="headerlink" title="解决方案"></a>解决方案</h2><ol>
<li>新建workspace专门用于python3的编译</li>
<li>进行<code>catkin config</code></li>
</ol>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">catkin config -DPYTHON_EXECUTABLE&#x3D;&#x2F;usr&#x2F;bin&#x2F;python3 -DPYTHON_INCLUDE_DIR&#x3D;&#x2F;usr&#x2F;include&#x2F;python3.5m -DPYTHON_LIBRARY&#x3D;&#x2F;usr&#x2F;lib&#x2F;x86_64-linux-gnu&#x2F;libpython3.5m.so</span><br><span class="line">catkin config --install</span><br></pre></td></tr></table></figure>
<ol start="3">
<li>拉取vision_opencv代码</li>
</ol>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">mkdir src</span><br><span class="line">cd src</span><br><span class="line">git clone -b kinetic https:&#x2F;&#x2F;github.com&#x2F;ros-perception&#x2F;vision_opencv.git</span><br></pre></td></tr></table></figure>

<ol start="4">
<li>编译</li>
</ol>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">cd ..</span><br><span class="line">catkin build cv_bridge</span><br></pre></td></tr></table></figure>

<h2 id="问题解决"><a href="#问题解决" class="headerlink" title="问题解决"></a>问题解决</h2><h3 id="解决编译中出现的Boost问题"><a href="#解决编译中出现的Boost问题" class="headerlink" title="解决编译中出现的Boost问题"></a>解决编译中出现的Boost问题</h3><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">Errors     &lt;&lt; cv_bridge:cmake &#x2F;home&#x2F;helei&#x2F;catkin_py3&#x2F;logs&#x2F;cv_bridge&#x2F;build.cmake.000.log    </span><br><span class="line">CMake Error at &#x2F;usr&#x2F;local&#x2F;share&#x2F;cmake-3.16&#x2F;Modules&#x2F;FindPackageHandleStandardArgs.cmake:146 (message):</span><br><span class="line">  Could NOT find Boost (missing: python3) (found version &quot;1.58.0&quot;)</span><br><span class="line">Call Stack (most recent call first):</span><br><span class="line">  &#x2F;usr&#x2F;local&#x2F;share&#x2F;cmake-3.16&#x2F;Modules&#x2F;FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)</span><br><span class="line">  &#x2F;usr&#x2F;local&#x2F;share&#x2F;cmake-3.16&#x2F;Modules&#x2F;FindBoost.cmake:2165 (find_package_handle_standard_args)</span><br><span class="line">  CMakeLists.txt:11 (find_package)</span><br></pre></td></tr></table></figure>

<p>解决办法：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">&#x2F;&#x2F;到libboost_python-py35所在文件夹下，建立软连接</span><br><span class="line">cd &#x2F;usr&#x2F;lib&#x2F;x86_64-linux-gnu&#x2F;</span><br><span class="line">sudo ln -s libboost_python-py35.so libboost_python3.so</span><br><span class="line">sudo ln -s libboost_python-py35.a libboost_python3.a</span><br></pre></td></tr></table></figure>

<p>ref: <a target="_blank" rel="noopener" href="https://blog.csdn.net/qq_42138662/article/details/105677869">https://blog.csdn.net/qq_42138662/article/details/105677869</a></p>
<h3 id="libgcc-s-so-1问题"><a href="#libgcc-s-so-1问题" class="headerlink" title="libgcc_s.so.1问题"></a>libgcc_s.so.1问题</h3><p><code>libgcc_s.so.1 must be installed for pthread_cancel to work</code></p>
<p>使用调试发现，问题仍然出在<code>import cv2</code>这个语句中。<br>在命令行中<code>echo $PYTHONPATH</code>可以发现：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">&#x2F;home&#x2F;helei&#x2F;catkin_py3&#x2F;devel&#x2F;lib&#x2F;python3&#x2F;dist-packages:&#x2F;home&#x2F;helei&#x2F;catkin_ws_rl&#x2F;devel&#x2F;lib&#x2F;python3&#x2F;dist-packages:&#x2F;home&#x2F;helei&#x2F;catkin_avoidance&#x2F;devel&#x2F;lib&#x2F;python2.7&#x2F;dist-packages:&#x2F;opt&#x2F;ros&#x2F;kinetic&#x2F;lib&#x2F;python2.7&#x2F;dist-packages</span><br></pre></td></tr></table></figure>

<p>也就是ros安装时候的<code>python2.7/dist-packages</code>仍然在环境中，而里面的<code>cv2.so</code>是python2.7的</p>
<p>解决方法：<br>如果以后不需要用到python2.7，则可以将2.7中的cv2.so删除<br><code>rm /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so</code></p>
<p>或者重命名：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">cd &#x2F;opt&#x2F;ros&#x2F;kinetic&#x2F;lib&#x2F;python2.7&#x2F;dist-packages</span><br><span class="line">mv cv2.so cv2_backup.so</span><br></pre></td></tr></table></figure>

<p>然后需要的时候再重命名回来就好。</p>
<h3 id="tf2-问题"><a href="#tf2-问题" class="headerlink" title="tf2 问题"></a>tf2 问题</h3><p>需要在python3中用到tf包<br><code>from tf.transformations import euler_from_quaternion, quaternion_from_euler</code></p>
<p>出现以下问题：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;&#x2F;home&#x2F;helei&#x2F;catkin_ws_rl&#x2F;src&#x2F;explainable_rl_ros&#x2F;scripts&#x2F;model_evaluation.py&quot;, line 21, in &lt;module&gt;</span><br><span class="line">    from tf.transformations import euler_from_quaternion, quaternion_from_euler</span><br><span class="line">  File &quot;&#x2F;opt&#x2F;ros&#x2F;kinetic&#x2F;lib&#x2F;python2.7&#x2F;dist-packages&#x2F;tf&#x2F;__init__.py&quot;, line 28, in &lt;module&gt;</span><br><span class="line">    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException</span><br><span class="line">  File &quot;&#x2F;opt&#x2F;ros&#x2F;kinetic&#x2F;lib&#x2F;python2.7&#x2F;dist-packages&#x2F;tf2_ros&#x2F;__init__.py&quot;, line 38, in &lt;module&gt;</span><br><span class="line">    from tf2_py import *</span><br><span class="line">  File &quot;&#x2F;opt&#x2F;ros&#x2F;kinetic&#x2F;lib&#x2F;python2.7&#x2F;dist-packages&#x2F;tf2_py&#x2F;__init__.py&quot;, line 38, in &lt;module&gt;</span><br><span class="line">    from ._tf2 import *</span><br><span class="line">ImportError: dynamic module does not define module export function (PyInit__tf2)</span><br></pre></td></tr></table></figure>

<p>解决： 下载geometry和geometry2 然后用python3编译，注意版本不能过高</p>
<p>ref：<br><a target="_blank" rel="noopener" href="https://answers.ros.org/question/326226/importerror-dynamic-module-does-not-define-module-export-function-pyinit__tf2/">https://answers.ros.org/question/326226/importerror-dynamic-module-does-not-define-module-export-function-pyinit__tf2/</a></p>
<p>然而，解决了上述问题之后，原来的avoidance编译是用的python2，所以又会报错：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;&#x2F;opt&#x2F;ros&#x2F;kinetic&#x2F;lib&#x2F;gazebo_ros&#x2F;spawn_model&quot;, line 32, in &lt;module&gt;</span><br><span class="line">    import tf.transformations as tft</span><br><span class="line">  File &quot;&#x2F;home&#x2F;helei&#x2F;catkin_py3&#x2F;devel&#x2F;lib&#x2F;python3&#x2F;dist-packages&#x2F;tf&#x2F;__init__.py&quot;, line 35, in &lt;module&gt;</span><br><span class="line">    exec(__fh.read())</span><br><span class="line">  File &quot;&lt;string&gt;&quot;, line 30, in &lt;module&gt;</span><br><span class="line">  File &quot;&#x2F;home&#x2F;helei&#x2F;catkin_py3&#x2F;devel&#x2F;lib&#x2F;python3&#x2F;dist-packages&#x2F;tf2_ros&#x2F;__init__.py&quot;, line 35, in &lt;module&gt;</span><br><span class="line">    exec(__fh.read())</span><br><span class="line">  File &quot;&lt;string&gt;&quot;, line 38, in &lt;module&gt;</span><br><span class="line">  File &quot;&#x2F;home&#x2F;helei&#x2F;catkin_py3&#x2F;devel&#x2F;lib&#x2F;python3&#x2F;dist-packages&#x2F;tf2_py&#x2F;__init__.py&quot;, line 35, in &lt;module&gt;</span><br><span class="line">    exec(__fh.read())</span><br><span class="line">  File &quot;&lt;string&gt;&quot;, line 38, in &lt;module&gt;</span><br><span class="line">ImportError: dynamic module does not define init function (init_tf2)</span><br></pre></td></tr></table></figure>

<p>ros官方对于python3的解释：<br><a target="_blank" rel="noopener" href="http://wiki.ros.org/UsingPython3">http://wiki.ros.org/UsingPython3</a></p>
<h3 id="build-px4-avoidance-with-python3"><a href="#build-px4-avoidance-with-python3" class="headerlink" title="build px4 avoidance with python3"></a>build px4 avoidance with python3</h3><p>需要先在进行<code>catkin config</code>到python3上<br>随后<code>catkin build avoidance</code><br>然后<code>source devel/setup.bash</code><br>然后再<code>catkin build</code></p>

      
    </div>
    <footer>
      
        
        
  
  <div class="tags">
    <a href="/tags/ROS/">ROS</a>
  </div>

        
  <div class="addthis addthis_toolbox addthis_default_style">
    
      <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
    
    
      <a class="addthis_button_tweet"></a>
    
    
      <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
    
    
      <a class="addthis_button_pinterest_pinit" pi:pinit:layout="horizontal"></a>
    
    <a class="addthis_counter addthis_pill_style"></a>
  </div>
  <script src="//s7.addthis.com/js/300/addthis_widget.js"></script>

      
      <div class="clearfix"></div>
    </footer>
  </div>
</article>


<section id="comment">
  <h1 class="title">Comments</h1>

  
      <div id="fb-root"></div>
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=123456789012345";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<div class="fb-comments" data-href="http://yoursite.com/2020/08/30/ros-python3/index.html" data-num-posts="5" data-width="840" data-colorscheme="light"></div>
      
  
</section>

</div></div>
    <aside id="sidebar" class="alignright">
  <div class="search">
  <form action="//google.com/search" method="get" accept-charset="utf-8">
    <input type="search" name="q" results="0" placeholder="Search">
    <input type="hidden" name="as_sitesearch" value="yoursite.com">
  </form>
</div>


  

  
<div class="widget tag">
  <h3 class="title">Tags</h3>
  <ul class="entry">
  
    <li><a href="/tags/ROS/">ROS</a><small>2</small></li>
  
    <li><a href="/tags/%E9%9A%8F%E7%AC%94/">随笔</a><small>1</small></li>
  
  </ul>
</div>

</aside>
    <div class="clearfix"></div>
  </div>
  <footer id="footer" class="inner"><div class="alignleft">
  
  &copy; 2020 John Doe
  
</div>
<div class="clearfix"></div></footer>
  
<script src="/js/jquery-3.4.1.min.js"></script>


<script src="/js/jquery.imagesloaded.min.js"></script>


<script src="/js/gallery.js"></script>






<link rel="stylesheet" href="/fancybox/jquery.fancybox.css">


<script src="/fancybox/jquery.fancybox.pack.js"></script>

<script>
(function($){
  $('.fancybox').fancybox();
})(jQuery);
</script>

</body>
</html>
